name: Build and publish Docker image

on:
  push:
    branches:
      - main

env:
  VERSION: "21.0"
  SPI_VERSION: "3.0.0"
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: |
            TITLE=Keycloak with SPI
            VCS_URL=${{ github.repository }}
            BUILD_DATE=${{ steps.date.outputs.date }}
            VERSION=${{ env.VERSION }}
          tags: |
            "ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:${{ env.VERSION }}"
            "ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:latest"
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
